In [1]:
import numpy as np
import scipy.sparse as sps
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize, MaxAbsScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn import svm
from sklearn.decomposition import TruncatedSVD
from sklearn import linear_model
from sklearn.neural_network import MLPClassifier

In [24]:
def train_test_LR(featMap, trueLabels, testSize=.33):
    train, test, train_labels, test_labels = train_test_split(featMap,trueLabels,test_size=testSize,random_state=42)
    train = MaxAbsScaler().fit_transform(train)
    test = MaxAbsScaler().fit_transform(test)
    
    clf = linear_model.SGDClassifier()#(verbose=True)
    clf.fit(train, train_labels)
    test_predict = clf.predict(test)
    
    confMat = confusion_matrix(test_labels,test_predict).astype(float)
    normConfMat = confMat.copy()
    normConfMat[0,:] /= confMat[0,:].sum()
    normConfMat[1,:] /= confMat[1,:].sum()
    return confMat, normConfMat, clf.score(test, test_labels)

In [3]:
city = 'London_'
prefix = './Datasets/'
datasets1 = [prefix + '3WordThresholdedEnglishReviews', 
             prefix + '3WordThresholdedEnglishReviews_k123', 
             prefix + 'EnglishReviews', 
             prefix + 'EnglishReviews_k123']

prefix = './Datasets_City/'+city
datasets2 = [prefix + 'UkReviews_Thresholded_BOW3', 
             prefix + 'UkReviews_Thresholded_BOW123', 
             prefix + 'UkReviews_Raw_BOW3', 
             prefix + 'UkReviews_Raw_BOW123']

In [7]:
featureMatrix = sps.load_npz(datasets2[0]+'_Features.npz')
#featureMatrix = min_max_scaler.fit_transform(featureMatrix)
labels = np.load(datasets2[0]+'_Labels.npz')['arr_0']
train, test, train_labels, test_labels = train_test_split(featureMatrix,labels,test_size=.33,random_state=42)
train = MaxAbsScaler().fit_transform(train)
test = MaxAbsScaler().fit_transform(test)

In [18]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(100), random_state=1, verbose=True)

In [19]:
clf.fit(train, train_labels)

MemoryError: 

In [16]:
test_predict = clf.predict(train)
    
confMat = confusion_matrix(train_labels,test_predict).astype(float)
normConfMat = confMat.copy()
normConfMat[0,:] /= confMat[0,:].sum()
normConfMat[1,:] /= confMat[1,:].sum()
print confMat
print normConfMat
print clf.score(test, test_labels)

[[     0.  63844.]
 [     0.  79881.]]
[[ 0.  1.]
 [ 0.  1.]]
0.553623393135


In [11]:
clf.predict()

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

In [5]:
featureMatrix.shape

(214515, 1871039)

# For Cities

In [25]:
results = []
for i in range(len(datasets2)):
    min_max_scaler = MaxAbsScaler()
    print "\n\n"
    print "Loading and normalizing dataset: "+ datasets2[i]
    featureMatrix = sps.load_npz(datasets2[i]+'_Features.npz')
    #featureMatrix = min_max_scaler.fit_transform(featureMatrix)
    labels = np.load(datasets2[i]+'_Labels.npz')['arr_0']
    print "SGD on "+ datasets2[i]
    cm, ncm, sc = train_test_LR(featureMatrix, labels)
    print "    Normalized Confusion Matrix:"
    print "    ", ncm[0,0], ncm[0,1]
    print "    ", ncm[1,0], ncm[1,1]
    print "    Accuracy: ", sc
    results.append([datasets2[i], cm.copy(), ncm.copy(), sc])




Loading and normalizing dataset: ./Datasets_City/London_UkReviews_Thresholded_BOW3
SGD on ./Datasets_City/London_UkReviews_Thresholded_BOW3
    Normalized Confusion Matrix:
     0.630652868762 0.369347131238
     0.0374575795463 0.962542420454
    Accuracy:  0.814394688515



Loading and normalizing dataset: ./Datasets_City/London_UkReviews_Thresholded_BOW123
SGD on ./Datasets_City/London_UkReviews_Thresholded_BOW123
    Normalized Confusion Matrix:
     0.963131744675 0.0368682553245
     0.0568753030032 0.943124696997
    Accuracy:  0.952055375053



Loading and normalizing dataset: ./Datasets_City/London_UkReviews_Raw_BOW3
SGD on ./Datasets_City/London_UkReviews_Raw_BOW3
    Normalized Confusion Matrix:
     0.457767507999 0.542232492001
     0.0141921978392 0.985807802161
    Accuracy:  0.722043168278



Loading and normalizing dataset: ./Datasets_City/London_UkReviews_Raw_BOW123
SGD on ./Datasets_City/London_UkReviews_Raw_BOW123
    Normalized Confusion Matrix:
     0.957891930